### ISSUE TITLE
vscode debug

### ISSUE THREAD

**Issue by dtelaroli** [pha3l/generator-aws-sam-typescript#1]
It's possible debug with vscode? Any exemple?

**Comment by pha3l** [comment]
It's definitely possible using the SAM cli `local invoke` with the `-d` option to connect to VSCode's debugger.  This is a pretty outdated configuration and was written before SAM cli even existed so it's not set up out of the box.

I can work on updating it if it would be helpful to you, I don't think it would be a huge effort.

**Comment by dtelaroli** [comment]
Oh ok!

I forgot the possibility of use command line, because I'm used to run the sam project with vscode aws toolkit.

Thank you.
